### ISSUE TITLE
No exit on dice string error

### ISSUE THREAD

**Issue by 5n8ke** [sstrickl/rolldice#20]
With commit 25f64b3ac37c887c321ee758425faf7d74cda9b8 rolldice does no longer exit on dice string errors. Since parse_string() can no longer modify variable dice_nums in roll_from_X().

**Comment by 5n8ke** [comment]
Fixed by me in my fork with b6d3e3355b64ba24d8655e5eb6f7d85502031eb1 but includes my changes to parse_from_stdin() from #19 .

**Comment by sstrickl** [comment]
Thanks!  I've merged your pull request, so this should be fixed now.
